class Status {
  static const String REQUEST_FIND_PARKING_LOT = 'REQUEST_FIND_PARKING_LOT';
  static const String RESPONSE_FIND_PARKING_LOT = 'RESPONSE_FIND_PARKING_LOT';
  static const String REQUEST_BOOK_PARKING_LOT = 'REQUEST_BOOK_PARKING_LOT';
  static const String RESPONSE_BOOK_PARKING_LOT_ACCEPTED = 'RESPONSE_BOOK_PARKING_LOT_ACCEPTED';
  static const String RESPONSE_BOOK_PARKING_LOT_REJECTED = 'RESPONSE_BOOK_PARKING_LOT_REJECTED';
  static const String REQUEST_CHECK_IN_PARKING_LOT = 'REQUEST_CHECK_IN_PARKING_LOT';
  static const String RESPONSE_CHECK_IN_ACCEPTED_PARKING_LOT = 'RESPONSE_CHECK_IN_ACCEPTED_PARKING_LOT';
  static const String RESPONSE_CHECK_IN_REJECTED_PARKING_LOT = 'RESPONSE_CHECK_IN_REJECTED_PARKING_LOT';
  static const String REQUEST_CHECK_OUT_PARKING_LOT = 'REQUEST_CHECK_OUT_PARKING_LOT';
  static const String RESPONSE_CHECK_OUT_ACCEPTED_PARKING_LOT = 'RESPONSE_CHECK_OUT_ACCEPTED_PARKING_LOT';
  static const String RESPONSE_CHECK_OUT_REJECTED_PARKING_LOT = 'RESPONSE_CHECK_OUT_REJECTED_PARKING_LOT';
}