export enum RequestStatus {
  REQUEST_HELLO_WORLD = 'REQUEST_HELLO_WORLD',
  RESPONSE_HELLO_WORLD = 'RESPONSE_HELLO_WORLD',

  REQUEST_FIND_PARKING = 'REQUEST_FIND_PARKING',
  RESPONSE_FIND_PARKING = 'RESPONSE_FIND_PARKING',
  REQUEST_BOOK_PARKING = 'REQUEST_BOOK_PARKING',
  RESPONSE_BOOK_PARKING_ACCEPTED = 'RESPONSE_BOOK_PARKING_ACCEPTED',
  RESPONSE_BOOK_PARKING_REJECTED = 'RESPONSE_BOOK_PARKING_REJECTED',
  REQUEST_CHECK_IN_PARKING = 'REQUEST_CHECK_IN_PARKING',
  RESPONSE_CHECK_IN_ACCEPTED_PARKING = 'RESPONSE_CHECK_IN_ACCEPTED_PARKING',
  RESPONSE_CHECK_IN_REJECTED_PARKING = 'RESPONSE_CHECK_IN_REJECTED_PARKING',
  REQUEST_CHECK_OUT_PARKING = 'REQUEST_CHECK_OUT_PARKING',
  RESPONSE_CHECK_OUT_ACCEPTED_PARKING = 'RESPONSE_CHECK_OUT_ACCEPTED_PARKING',
  RESPONSE_CHECK_OUT_REJECTED_PARKING = 'RESPONSE_CHECK_OUT_REJECTED_PARKING',
}
