export enum RequestStatus {
  REQUEST_HELLO_WORLD = 'REQUEST_HELLO_WORLD',
  RESPONSE_HELLO_WORLD = 'RESPONSE_HELLO_WORLD',

  REQUEST_FIND_PARKING_LOT = 'REQUEST_FIND_PARKING_LOT',
  RESPONSE_FIND_PARKING_LOT = 'RESPONSE_FIND_PARKING_LOT',
  REQUEST_BOOK_PARKING_LOT = 'REQUEST_BOOK_PARKING_LOT',
  RESPONSE_BOOK_PARKING_LOT_ACCEPTED = 'RESPONSE_BOOK_PARKING_LOT_ACCEPTED',
  RESPONSE_BOOK_PARKING_LOT_REJECTED = 'RESPONSE_BOOK_PARKING_LOT_REJECTED',
  REQUEST_CHECK_IN_PARKING_LOT = 'REQUEST_CHECK_IN_PARKING_LOT',
  RESPONSE_CHECK_IN_ACCEPTED_PARKING_LOT = 'RESPONSE_CHECK_IN_ACCEPTED_PARKING_LOT',
  RESPONSE_CHECK_IN_REJECTED_PARKING_LOT = 'RESPONSE_CHECK_IN_REJECTED_PARKING_LOT',
  REQUEST_CHECK_OUT_PARKING_LOT = 'REQUEST_CHECK_OUT_PARKING_LOT',
  RESPONSE_CHECK_OUT_ACCEPTED_PARKING_LOT = 'RESPONSE_CHECK_OUT_ACCEPTED_PARKING_LOT',
  RESPONSE_CHECK_OUT_REJECTED_PARKING_LOT = 'RESPONSE_CHECK_OUT_REJECTED_PARKING_LOT',
}
